### ISSUE TITLE
Bug: `zlib.deflate` results in a segmentation fault

### ISSUE THREAD

**Issue by zyscoder** [fibjs/fibjs#650] opened 2021-04-12 10:18 UTC
# Bug Report
* **Version**: v0.32.1
* **Platform**:  Linux 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: zlib.deflate

### What steps will reproduce the bug?
Setup a fibjs instance,
```
» fibjs
```
and run the following javascript code.
```
zlib = require('zlib');zlib.deflate(undefined,31);
```
Then the fibjs instance occurs a segmentation fault.

### How often does it reproduce? Is there a required condition?
This problem can always be triggered following the steps above.

### What is the expected behavior?
If any error occurs, an exception or other similar error-reporting stuff should be thrown just like node.js. There is no reason to crash the whole fibjs process.

### What do you see instead?
```
» fibjs
Welcome to fibjs 0.32.1.
Type ".help" for more information.
> zlib = require('zlib');zlib.deflate(undefined,31);
[1]    17301 segmentation fault (core dumped)  fibjs                                                                                                                                                                                                 
```

**Comment by xicilion** [comment] 2021-04-12 13:39
This error disappeared under v0.33-dev, I suspect it was caused by the zlib upgrade, and I am still checking it.

**Comment by xicilion** [comment] 2021-04-12 13:51
This is a zlib bug, and it has been fixed now. 3854a49c10a4eaddd1a0dc27329a6b0bc93e00d5

**Comment by xicilion** [comment] 2021-04-12 14:26
fixed. d824ad7da0e5ef42a2ccfcd3e2a11bf71bf55eb6

**Closed** 2021-04-13 04:18 UTC
Labels: bug
